const api = async (path, options = {}) => {
  const response = await fetch(path, { headers: { "Content-Type": "application/json", "X-Actor": $("actor")?.value || "web-user", "X-Request-ID": crypto.randomUUID() }, ...options });
  if (response.status === 304) return { message: "本地档案仍为最新" };
  const result = await response.json();
  if (!response.ok) throw new Error(result.message || result.error);
  return result;
};
const $ = id => document.getElementById(id);
const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let current;
let packagePreview;
let archiveCursor="";
const impactFilter={severity:"",type:"",channel:""};
async function loadRuns() {
  const q = new URLSearchParams(); if ($("status").value) q.set("status", $("status").value); if ($("engine").value) q.set("engine_ref", $("engine").value); if ($("blocking").checked) q.set("has_blocking", "true");
  try { const data = await api("/api/runs?" + q); $("runs").innerHTML = data.runs.length ? data.runs.map(r => `<button class="run" data-id="${esc(r.ID || r.id)}"><strong>${esc(r.EngineRef || r.engine_ref)}</strong> · ${esc(r.Status || r.status)}<br>待分诊 ${r.PendingTriage ?? r.pending_triage ?? 0} · 待修订 ${r.PendingEvidence ?? r.pending_evidence ?? 0} · 开放阻断 ${r.OpenBlocking ?? r.open_blocking ?? 0}</button>`).join("") : "没有符合条件的试车任务"; document.querySelectorAll(".run").forEach(x => x.onclick = () => detail(x.dataset.id)); } catch(e) { $("runs").textContent = "加载失败：" + e.message; }
}
async function detail(id) {
  try { current = await api(`/api/runs/${id}`); const r=current.test_run; $("detail").hidden=false; $("summary").innerHTML=`<p><strong>${esc(r.engine_ref)}</strong> · ${esc(r.rig_id)} · ${esc(r.status)} · revision ${r.revision}</p><p>${esc(r.objective)} · ${esc(r.scheduled_start)} — ${esc(r.scheduled_end)}</p>`; $("output").textContent=JSON.stringify({packages:current.data_packages,anomalies:current.anomalies,evidence:current.evidence,reviews:current.reviews,audit:current.audit},null,2); renderActions(r); await renderAnalysis(r); } catch(e){$("output").textContent=e.message;}
}
function renderActions(r) {
  const a=$("actions"); a.innerHTML="";
  if(r.status==="DRAFT") a.innerHTML=`<button id="precheck">冻结预检</button><button id="freeze" disabled>确认冻结</button><pre id="precheckOut"></pre>`;
  if(r.status==="BASELINED") { const seconds=Math.max(1,Math.floor((new Date(r.scheduled_end)-new Date(r.scheduled_start))/1000)); const channels=(r.expected_channels||[]).map(name=>({name,samples:seconds,sample_rate_hz:1,min:0,max:1})); const body={expected_revision:r.revision,capture_start:r.scheduled_start,capture_end:r.scheduled_end,clock_drift_ms:0,files:[{name:"capture.dat",digest:"sha256-digest",bytes:1}],channel_summaries:channels,duplicate_segments:[]}; a.innerHTML=`<div class="panel"><h3>数据包登记</h3><textarea id="packageBody">${esc(JSON.stringify(body,null,2))}</textarea><div class="panel-actions"><button id="packagePreview">预演</button><button id="packageConfirm" disabled>确认登记</button></div><pre id="precheckOut"></pre></div>`; }
  if(r.status==="REVIEW_PENDING") { const checklist=(current.anomalies||[]).map(x=>({anomaly_id:x.id,data_package_confirmed:true,gate_confirmed:true,impact_confirmed:true,evidence_confirmed:true,before_after_confirmed:true,passed:true})); a.innerHTML=`<div class="panel"><h3>独立复核</h3><textarea id="reviewBody">${esc(JSON.stringify({expected_revision:r.revision,outcome:"APPROVED",notes:"",comparison_review_id:"",checklist,targets:[]},null,2))}</textarea><div class="panel-actions"><button id="reviewSubmit">提交复核</button></div><pre id="precheckOut"></pre></div>`; }
  if(r.status==="REVIEWED") a.innerHTML=`<div class="panel"><h3>有效性裁定</h3><button id="ready">裁定就绪检查</button><textarea id="decisionBody">${esc(JSON.stringify({expected_revision:r.revision,verdict:"VALID",applicable_objectives:[r.objective],limitations:[]},null,2))}</textarea><button id="decisionSubmit">签发裁定</button><pre id="precheckOut"></pre></div>`;
  if(r.status==="DECIDED") a.innerHTML=`<button id="archiveSubmit">确认封存</button><pre id="precheckOut"></pre>`;
  if(r.status==="ARCHIVED") a.innerHTML=`<button id="verify">完整性校验</button><a class="button" href="/api/runs/${r.id}/archive">下载档案</a><pre id="precheckOut"></pre>`;
  if($("precheck")) $("precheck").onclick=async()=>{try{const p=await api(`/api/runs/${r.id}/baseline`);$("precheckOut").textContent=JSON.stringify(p,null,2);$("freeze").disabled=false;$("freeze").onclick=async()=>{await api(`/api/runs/${r.id}/baseline`,{method:"POST",body:JSON.stringify({expected_revision:p.revision,candidate_baseline_hash:p.candidate_baseline_hash})});detail(r.id);};}catch(e){$("precheckOut").textContent=e.message;}};
  if($("ready")) $("ready").onclick=async()=>{$("precheckOut").textContent=JSON.stringify(await api(`/api/runs/${r.id}/decision`),null,2);};
  if($("reviewSubmit")) $("reviewSubmit").onclick=async()=>{try{const body=JSON.parse($("reviewBody").value);const diff=await api(`/api/runs/${r.id}/review`);body.expected_revision=r.revision;body.comparison_review_id=diff.comparison_review_id;await api(`/api/runs/${r.id}/review`,{method:"POST",body:JSON.stringify(body)});await detail(r.id);}catch(e){$("precheckOut").textContent="复核未提交："+e.message;}};
  if($("decisionSubmit")) $("decisionSubmit").onclick=async()=>{try{await api(`/api/runs/${r.id}/decision`,{method:"POST",body:JSON.stringify(JSON.parse($("decisionBody").value))});await detail(r.id);}catch(e){$("precheckOut").textContent="裁定未签发："+e.message;}};
  if($("archiveSubmit")) $("archiveSubmit").onclick=async()=>{try{await api(`/api/runs/${r.id}/archive`,{method:"POST",body:JSON.stringify({expected_revision:r.revision})});await detail(r.id);}catch(e){$("precheckOut").textContent="封存失败："+e.message;}};
  if($("verify")) $("verify").onclick=async()=>{$("precheckOut").textContent=JSON.stringify(await api(`/api/runs/${r.id}/archive?report=true`),null,2);};
  if($("packagePreview")) $("packagePreview").onclick=async()=>{try{const body=JSON.parse($("packageBody").value);packagePreview=await api(`/api/runs/${r.id}/package`,{method:"PUT",body:JSON.stringify(body)});$("precheckOut").textContent=JSON.stringify(packagePreview,null,2);$("packageConfirm").disabled=false;}catch(e){packagePreview=null;$("packageConfirm").disabled=true;$("precheckOut").textContent=e.message;}};
  if($("packageConfirm")) $("packageConfirm").onclick=async()=>{try{const body=JSON.parse($("packageBody").value);body.expected_revision=packagePreview.revision;body.candidate_package_hash=packagePreview.candidate_package_hash;await api(`/api/runs/${r.id}/package`,{method:"POST",body:JSON.stringify(body)});packagePreview=null;await detail(r.id);}catch(e){$("precheckOut").textContent="确认失败，已重新加载预演："+e.message;$("packageConfirm").disabled=true;try{$("packagePreview").click();}catch(_){}}};
}
async function renderAnalysis(r){
  const evidenceItems=(current.anomalies||[]).filter(a=>a.status==="TRIAGED"||a.status==="NEEDS_REVISION").map(a=>{const old=(current.evidence||[]).filter(e=>e.anomaly_id===a.id&&!e.replaced_by).sort((x,y)=>new Date(y.submitted_at)-new Date(x.submitted_at))[0];return {anomaly_id:a.id,method:"EXCLUDE",rationale:"",before_digest:"",after_digest:"",evidence_refs:[],supersedes_evidence_id:a.status==="NEEDS_REVISION"?(old?.id||""):"",risk_statement:""}});
  const triageItems=(current.anomalies||[]).filter(a=>a.status==="OPEN").map(a=>({anomaly_id:a.id,kind:a.kind,severity:a.severity,impact_statement:a.impact_statement||"",disposition:"待处置",time_range:a.time_range,affected_channels:a.affected_channels||[]}));
  const v=$("analysisViews"); v.innerHTML=`<div class="panel"><h3>异常影响矩阵、重叠组与处置优先级</h3><div class="toolbar"><select id="impactSeverity"><option value="">全部严重度</option><option>BLOCKING</option><option>MAJOR</option><option>MINOR</option></select><select id="impactType"><option value="">全部类型</option><option value="data_gap">data_gap</option><option value="out_of_range">out_of_range</option><option value="drift">drift</option><option value="duplicate">duplicate</option><option value="quality_gate">quality_gate</option></select><input id="impactChannel" placeholder="冻结测点"></div><div class="panel-actions"><button id="loadImpact">刷新矩阵</button><button id="loadEvidence">闭环预检</button>${r.status==="REVIEW_PENDING"?'<button id="loadDiff">再审差异</button>':''}</div><pre id="analysisOut">等待查询</pre></div>${triageItems.length?`<div class="panel"><h3>批量异常分诊</h3><textarea id="triageItems">${esc(JSON.stringify(triageItems,null,2))}</textarea><button id="submitTriage">原子分诊</button><pre id="triageOut"></pre></div>`:""}${evidenceItems.length?`<div class="panel"><h3>批量处置证据</h3><textarea id="evidenceItems">${esc(JSON.stringify(evidenceItems,null,2))}</textarea><div class="panel-actions"><button id="submitEvidence">原子提交</button></div><pre id="evidenceOut"></pre></div>`:""}`;
  $("impactSeverity").value=impactFilter.severity;$("impactType").value=impactFilter.type;$("impactChannel").value=impactFilter.channel;
  $("loadImpact").onclick=async()=>{try{impactFilter.severity=$("impactSeverity").value;impactFilter.type=$("impactType").value;impactFilter.channel=$("impactChannel").value;const q=new URLSearchParams();Object.entries(impactFilter).forEach(([k,v])=>{if(v)q.set(k,v)});$("analysisOut").textContent=JSON.stringify(await api(`/api/runs/${r.id}/anomaly-impact?${q}`),null,2);}catch(e){$("analysisOut").textContent="矩阵加载失败："+e.message;}};
  $("loadEvidence").onclick=async()=>{try{$("analysisOut").textContent=JSON.stringify(await api(`/api/runs/${r.id}/evidence`),null,2);}catch(e){$("analysisOut").textContent="预检失败："+e.message;}};
  if($("loadDiff")) $("loadDiff").onclick=async()=>{try{$("analysisOut").textContent=JSON.stringify(await api(`/api/runs/${r.id}/review`),null,2);}catch(e){$("analysisOut").textContent="差异加载失败："+e.message;}};
  if($("submitEvidence")) $("submitEvidence").onclick=async()=>{try{const items=JSON.parse($("evidenceItems").value);const result=await api(`/api/runs/${r.id}/evidence`,{method:"POST",body:JSON.stringify({expected_revision:r.revision,items})});$("evidenceOut").textContent=JSON.stringify(result,null,2);await detail(r.id);}catch(e){$("evidenceOut").textContent="整批未提交："+e.message;}};
  if($("submitTriage")) $("submitTriage").onclick=async()=>{try{await api(`/api/runs/${r.id}/triage`,{method:"POST",body:JSON.stringify({expected_revision:r.revision,items:JSON.parse($("triageItems").value)})});await detail(r.id);}catch(e){$("triageOut").textContent="整批未分诊："+e.message;}};
  await $("loadImpact").onclick();
}
async function loadArchives(more=false){
  const q=new URLSearchParams();if($("archiveVerdict").value)q.set("verdict",$("archiveVerdict").value);if($("archiveRig").value)q.set("rig_id",$("archiveRig").value);if($("archiveEngine").value)q.set("engine_ref",$("archiveEngine").value);if($("archiveObjective").value)q.set("objective",$("archiveObjective").value);if($("archiveSigner").value)q.set("signed_by",$("archiveSigner").value);if($("archiveFrom").value)q.set("signed_from",new Date($("archiveFrom").value).toISOString());if($("archiveTo").value)q.set("signed_to",new Date($("archiveTo").value).toISOString());if($("archiveLimited").checked)q.set("has_limitations","true");if(more&&archiveCursor)q.set("cursor",archiveCursor);
  try{const d=await api("/api/archives?"+q);$("archiveStats").innerHTML=[["VALID",d.stats.valid],["INVALID",d.stats.invalid],["有限制",d.stats.with_limitations],["含重大或阻断异常",d.stats.with_major_or_blocking_anomalies]].map(x=>`<div class="metric"><strong>${x[1]}</strong><br>${x[0]}</div>`).join("");const html=d.records.map(x=>`<div class="archive"><strong>${esc(x.engine_ref)}</strong> · ${esc(x.verdict)} · ${esc(x.signed_at)}<br>${esc(x.archive_hash)}<br><a href="${esc(x.download_url)}">下载</a> · <button data-detail="${esc(x.test_run_id)}">详情</button> · <a href="${esc(x.timeline_url)}">时间线</a></div>`).join("");$("archives").innerHTML=more?$("archives").innerHTML+html:(html||"没有符合条件的封存档案");archiveCursor=d.next_cursor||"";$("archiveMore").hidden=!archiveCursor;document.querySelectorAll("[data-detail]").forEach(x=>x.onclick=()=>{showTab("runs");detail(x.dataset.detail);});}catch(e){$("archives").textContent="台账加载失败："+e.message;}
}
function showTab(name){const runs=name==="runs";$("runsView").hidden=!runs;$("archivesView").hidden=runs;$("runsTab").classList.toggle("active",runs);$("archivesTab").classList.toggle("active",!runs);if(!runs){archiveCursor="";loadArchives();}}
$("refresh").onclick=loadRuns; $("clear").onclick=()=>{$("status").value="";$("engine").value="";$("blocking").checked=false;loadRuns();};
$("runsTab").onclick=()=>showTab("runs");$("archivesTab").onclick=()=>showTab("archives");$("archiveSearch").onclick=()=>{archiveCursor="";loadArchives();};$("archiveMore").onclick=()=>loadArchives(true);
api("/readyz").then(()=>{$("health").textContent="服务已连接";loadRuns();}).catch(()=>{$("health").textContent="服务不可用";});
